.gitignore
.gitmojirc.json
BE/.githooks/pre-commit
iOS/.githooks/pre-commit
setup

gitmoji의 이모지는 너무 많은 종류를 제공합니다.
- 사용하기로 정한 이모지만 리스트에 포함한 커스텀 리스트를 작성했습니다.
- 이모지 사용 설명을 한국어로 작성했습니다.
- .gitignore 추가
- githook 사용을 위한 베이스 세팅을 설정했습니다.
`gitmoji -l`로 리스트 확인 가능합니다.
깃모지 좋.아.
| 리스트 |
| :-: |
| <img width="483" alt="Screenshot 2023-11-06 at 21 33 31" src="https://github.com/boostcampwm2023/iOS01-Maybe-Gamsung/assets/138548400/4a05c50b-c587-41fa-914b-f9ff8c084da3"> |

[MGT-19] gitmoji 설정 & gitignore 추가 & githook 환경 세팅

---

README.md

리드미를 꾸며봤습니다..
예쁘죠? 어프루브 해주세요..

[Chore] 리드미 꾸미기

---

BE/musicspot/package-lock.json
BE/musicspot/package.json
BE/musicspot/src/main.ts

api 문서화 시스템 swaager를 설정합니다.
https://github.com/boostcampwm2023/iOS01-MusicSpot/issues/59
- swagger 설정
- swagger를 설치하고 설정합니다.

[BE] swagger 설정

---

BE/musicspot/src/journey/controller/journey.controller.ts
BE/musicspot/src/journey/dto/journeyCheck.dto.ts
BE/musicspot/src/journey/dto/journeySelect.dto.ts
BE/musicspot/src/journey/service/journey.service.ts
BE/musicspot/src/spot/service/spot.service.spec.ts

여정 조회 API
우선 client에서 userId와 minCoordinate, maxCoordinate를 요청 받습니다.
이후 좌표들을 기준으로 해당 범위를 결정을 짓습니다.
그 범위에 따라서 userId에 해당하는 여정들 중 해당 범위내에 있는 데이터들만 반환하는 방법으로 구현했습니다.

[BE] 여정 조회 API

---

BE/musicspot/.env
BE/musicspot/src/app.module.ts

config 파일에 의한 환경변수 충돌 제거
dotenv파일 제거

[BE} ♻️ : config 파일 제거

---

BE/musicspot/src/journey/controller/journey.controller.ts
BE/musicspot/src/journey/dto/journeyCheck.dto.ts
BE/musicspot/src/journey/dto/journeyCheckResponse.dto.ts
BE/musicspot/src/journey/dto/journeyEnd.dto.ts
BE/musicspot/src/journey/dto/journeyEndResponse.dto.ts
BE/musicspot/src/journey/service/journey.service.ts

예외 처리 및 스웨거 응답 코드를 추가했습니다. 여정 조회 알고리즘도 일부 수정했습니다.
스웨거 응답 부분 코드가 실제 형식에 맞지 않고 JourneyDTO 형식으로 되어 있어서 알맞은 형식에 맞게 새로운 DTO를 생성해서 지정하는 방식으로 했습니다.
예외 처리하는 부분에서 UsePipes와 isnotempty 제약 조건을 추가했습니다. 일단 여정 조회 부분에만 추가를 해둬서 이후 다른 부분에도 추가하면 어떨까 싶어서 추가해두었습니다.

[BE] 예외 처리 및 스웨거 응답 부분 추가

---

.github/workflows/action.yml
BE/musicspot/.env
BE/musicspot/src/app.module.ts
BE/musicspot/src/common/decorator/coordinate.decorator.ts
BE/musicspot/src/journey/controller/journey.controller.ts
BE/musicspot/src/journey/dto/journeyCheck.dto.ts
BE/musicspot/src/journey/dto/journeyCheckResponse.dto.ts
BE/musicspot/src/journey/dto/journeyEnd.dto.ts
BE/musicspot/src/journey/dto/journeyEndResponse.dto.ts
BE/musicspot/src/journey/dto/journeyRecord.dto.ts
BE/musicspot/src/journey/dto/journeyStart.dto.ts
BE/musicspot/src/journey/schema/journey.schema.ts
BE/musicspot/src/journey/service/journey.service.spec.ts
BE/musicspot/src/journey/service/journey.service.ts
BE/musicspot/src/spot/controller/spot.controller.ts
BE/musicspot/src/spot/dto/recordSpot.dto.ts
BE/musicspot/src/spot/service/spot.service.spec.ts

journey관련 service 오류 수정 필요
journey관련 예외처리 추가(journey not found)
관련 기타 비지니스 로직 수정(lean() 추가)
npm test src/journey/service/journey.service.spec.ts 를 하면 실행

[BE] ♻️ : journey관련 exception 추가

---

BE/musicspot/src/filters/exception.filter.ts

[BE]예외 필터 수정

---

BE/musicspot/package-lock.json
BE/musicspot/package.json
BE/musicspot/src/common/logger/winston.util.ts
BE/musicspot/src/filters/exception.filter.ts
BE/musicspot/src/main.ts

logger를 통한 모니터링 필요
winston 설정 및 추가
winston을 이용해서 info, warn, error를 나눠 기록합니다. 
docker 의 volume 기능을 통해 컨테이너가 삭제되어도 러그 파일은 그대로 남도록 유지합니다.

[BE] winston logger 추가

---

BE/musicspot/package-lock.json
BE/musicspot/package.json
BE/musicspot/src/common/logger/winston.util.ts
BE/musicspot/src/main.ts

[BE] logger 추가

---

BE/musicspot/src/filters/exception.enum.ts
BE/musicspot/src/filters/spot.exception.ts
BE/musicspot/src/journey/service/journey.service.ts
BE/musicspot/src/spot/controller/spot.controller.ts
BE/musicspot/src/spot/schema/spot.schema.ts
BE/musicspot/src/spot/service/spot.service.ts

spotid로 spot 가져오기 get 요청 구현 및 예외처리

[BE] spotid로 spot 가져오기 get 요청 구현 및 예외처리

---

BE/musicspot/package-lock.json
BE/musicspot/package.json
BE/musicspot/src/journey/controller/journey.controller.ts
BE/musicspot/src/journey/dto/journeyEnd.dto.ts
BE/musicspot/src/journey/dto/journeyLoad.dto.ts
BE/musicspot/src/journey/dto/journeyStart.dto.ts
BE/musicspot/src/journey/schema/journey.schema.ts
BE/musicspot/src/journey/service/journey.service.ts

여정 조회 방식 변경 및 가장 최근 여정 찾기 api 구현
여정 조회의 방식 경우 https://turfjs.org/ 를 참고해서 해당 모듈을 활용해서 구현하는 방식으로 변경했습니다
loadLastData api를 통해서 가장 최근에 기록되고 있던 여정을 조회할 수 있습니다.

[BE] 여정 조회 방식 변경 및 가장 최근 여정 찾기 api 구현

---

BE/musicspot/src/spot/service/spot.service.ts

spot 생성 시 응답 수정 필요
spot 생성 시 응답 수정 
- spot 생성 후 응답(생성된 데이터 -> 성공 실패 여부)
- 이유: spot 생성 후 클라이언트에서 데이터를 따로 반환받을 필요가 없음

[BE] ♻️ :spot 생성 시 응답 수정

---

BE/musicspot/src/journey/dto/journeyCheck/journeyCheck.dto.ts

journey check 시 metadata 추가 필요
journey check 시 metadata 추가
- journey check 시 metadata 추가 필요
- metadata : 시작 시간 및 종료 시간  

[BE] ♻️ : joruney check swagger 수정

---

iOS/Features/RewindJourney/Sources/RewindJourney/Presentation/Coordinator/RewindJourneyNavigationDelegate.swift
iOS/Features/RewindJourney/Sources/RewindJourney/Presentation/RewindJourneyViewController+Gesture.swift
iOS/Features/RewindJourney/Sources/RewindJourney/Presentation/RewindJourneyViewController.swift
iOS/MSData/Sources/MSData/DTO/Fragment/SpotDTO.swift
iOS/MusicSpot/MusicSpot/MSCoordinator/RewindJourneyCoordinator.swift

[iOS] Rewind 스와이프 뒤로가기 제스처 추가

---

.gitignore
.gitmojirc.json
BE/.githooks/pre-commit
BE/README.md
README.md
iOS/MSDomain/.swiftpm/xcode/package.xcworkspace/contents.xcworkspacedata
setup

- 삭제된 `README.md` 등의 문서를 복구 했습니다.

[iOS] 문서 복구

---

iOS/Features/Home/Sources/Home/Presentation/Coordinator/HomeNavigationDelegate.swift
iOS/Features/Home/Sources/Home/Presentation/HomeViewController.swift
iOS/Features/Home/Sources/Home/Presentation/HomeViewModel.swift
iOS/Features/Home/Sources/NavigateMap/Presentation/NavigateMapViewController.swift
iOS/Features/JourneyList/Sources/JourneyList/Presentation/JourneyListViewController.swift
iOS/Features/JourneyList/Sources/JourneyList/Presentation/VIew/MSCollectionView.swift
iOS/Features/Spot/Sources/Spot/Presentation/Coordinator/SpotNavigationDelegate.swift
iOS/Features/Spot/Sources/Spot/Presentation/SpotSaveViewModel.swift
iOS/Features/Spot/Sources/Spot/Presentation/SpotViewController.swift
iOS/Features/Spot/Sources/Spot/Presentation/SpotViewModel.swift
iOS/MSCoreKit/Sources/MSNetworking/HTTPBody.swift
iOS/MSData/Sources/MSData/DTO/Fragment/CoordinateDTO.swift
iOS/MSData/Sources/MSData/Repository/JourneyRepository.swift
iOS/MSData/Sources/MSData/Repository/SongRepository.swift
iOS/MSDomain/Sources/MSDomain/Model/Spot.swift
iOS/MusicSpot/MusicSpot.xcodeproj/project.pbxproj
iOS/MusicSpot/MusicSpot/MSCoordinator/HomeCoordinator.swift
iOS/MusicSpot/MusicSpot/MSCoordinator/SpotCoordinator.swift

- close #251 
- 여정 시작 네트워킹 로직 추가
- `CoordinateDTO` 인코딩 에러 수정
- `JourneyList` 스크롤 UX 개선

[iOS] 여정 시작 네트워킹 추가

---

iOS/Features/Home/Sources/Home/Presentation/HomeViewController.swift
iOS/Features/Home/Sources/Home/Presentation/HomeViewModel.swift
iOS/Features/Home/Sources/NavigateMap/Presentation/NavigateMapViewController.swift
iOS/Features/Home/Sources/NavigateMap/Presentation/NavigateMapViewModel.swift
iOS/Features/Spot/Sources/Spot/Presentation/SpotSaveViewController.swift
iOS/MSData/Sources/MSData/DTO/Request/Journey/RecordCoordinateRequestDTO.swift
iOS/MSData/Sources/MSData/Repository/JourneyRepository.swift
iOS/MSData/Sources/MSData/Router/Journey/JourneyRouter+Body.swift
iOS/MSData/Sources/MSData/Router/Journey/JourneyRouter+Method.swift
iOS/MSData/Sources/MSData/Router/Journey/JourneyRouter+URL.swift
iOS/MSData/Sources/MSData/Router/Journey/JourneyRouter.swift

- 네트워크로부터 데이터를 불러와서 지도 위에 표시하는 기능을 구현했습니다.
- 여정 중간에 위치를 저장하는 기능을 구현했습니다.

[iOS] 여정을 Map 위에 표시하는 기능 구현

---

iOS/Features/Home/Sources/Home/Presentation/HomeViewController.swift
iOS/Features/Home/Sources/Home/Presentation/HomeViewModel.swift
iOS/Features/Home/Sources/NavigateMap/Presentation/NavigateMap/NavigateMapViewModel.swift
iOS/Features/SaveJourney/Sources/SaveJourney/Presentation/SaveJourneyViewController.swift
iOS/Features/SaveJourney/Sources/SaveJourney/Presentation/SaveJourneyViewModel.swift
iOS/Features/SelectSong/Sources/SelectSong/Presentation/SelectSongViewModel.swift
iOS/MSUIKit/Sources/MSUIKit/MSBottomSheetViewController/MSBottomSheetViewController.swift

- 여정 시작 시 하단 여정 목록 숨김 처리
- 음악 순위 호출 시 로딩 인디케이터 추가
| 바텀 시트 |
| :-: |
| <img src="https://github.com/boostcampwm2023/iOS01-MusicSpot/assets/138548400/2f5457be-02a1-44be-861d-1c3f80707105" width="300"> |

[iOS] 작은 개선 사항들

---

iOS/MSCoreKit/Sources/MSPersistentStorage/CoreData/README.md
iOS/MSCoreKit/Sources/MSPersistentStorage/FileManager/FileManagerStorage.swift
iOS/MSCoreKit/Sources/MSPersistentStorage/Protocol/MSPersistentStorage.swift
iOS/MSCoreKit/Tests/MSPersistentStorageTests/FileManagerStorageTests.swift
iOS/MSData/Package.swift
iOS/MSData/Sources/MSData/Repository/LocalRepository.swift
iOS/MusicSpot/MusicSpot.xcodeproj/project.pbxproj

#274 
기록한 coordinate들을 로컬 저장소에 저장합니다.

[iOS] local storage

---

iOS/Features/RewindJourney/Sources/RewindJourney/Presentation/RewindJourneyViewController.swift
iOS/Features/Spot/Sources/Spot/Presentation/SpotSaveViewModel.swift
iOS/Features/Spot/Sources/Spot/Presentation/SpotViewController+Gesture.swift
iOS/Features/Spot/Sources/Spot/Presentation/SpotViewController.swift

- camera 아래로 내려서 취소하는 스크롤, 옆으로 쓸어서 이동하는 코드로 변경하기
- camera 촬영 시, 햅틱 진동 추가

[iOS] UI 버그 수정

---

.gitignore

[BE] main 브랜치 merge 충돌 해결

---

iOS/Features/Home/Sources/Home/Presentation/HomeViewController.swift
iOS/Features/Home/Sources/Home/Presentation/HomeViewModel.swift
iOS/Features/Home/Sources/NavigateMap/Presentation/Common/MapViewController.swift

- Home Scene에서 로직 면에서 문제가 있는 버그들을 수정했습니다.
- Spot 저장 후 화면 뒤로가기 버튼 클릭 시 지도 내 Spot 사라지도록 수정했습니다.
- 시작하기 후 여기에서 검색 버튼 숨김 처리했습니다.
- 기록 중인 상황에서는 지도로 좌표 이동 시 여기에서 검색 버튼 숨김 처리했습니다.
- 뒤로가기 버튼 클릭 시 여기에서 검색 버튼이 보이도록 처리했습니다.
- 여정 내 Spot Coordinate들도 Polyline에 표시되도록 추가하였습니다.

[iOS] Home 관련 Bug Fix 수정

---

iOS/Features/Home/Sources/Home/Presentation/HomeViewController.swift
iOS/Features/Home/Sources/NavigateMap/Presentation/Common/MapViewController+EventListener.swift
iOS/Features/Home/Sources/NavigateMap/Presentation/Common/MapViewController.swift

- 전보다는 나아진 것 같긴 한데 여전히 불안정합니다.
- ViewModel 바꿔칠 때 Logger 출력 추가했습니다.

[iOS] HomeViewController `isRecording` 관련 안정성 향상

---

iOS/Features/Home/Sources/NavigateMap/Presentation/Common/MapViewController.swift
iOS/Features/JourneyList/Sources/JourneyList/Presentation/JourneyListViewController.swift
iOS/Features/JourneyList/Sources/JourneyList/Presentation/VIew/JourneyListHeaderView.swift
iOS/Features/SaveJourney/Sources/SaveJourney/Presentation/SaveJourneyViewController.swift
iOS/Features/SaveJourney/Sources/SaveJourney/Presentation/SaveJourneyViewModel.swift
iOS/MusicSpot/MusicSpot.xcodeproj/project.pbxproj
iOS/MusicSpot/MusicSpot/SceneDelegate.swift

- 여정 목록 헤더 오류 수정
| 데모 영상 |
| :-: |
| <img src="https://github.com/boostcampwm2023/iOS01-MusicSpot/assets/138548400/b09352aa-1c66-4d42-a529-83d48ab4a141" width="300"> |

[iOS] 여정 목록 헤더 업데이트 오류 수정

---

iOS/Features/Home/Sources/Home/Presentation/HomeViewModel.swift
iOS/Features/Home/Sources/NavigateMap/Presentation/Common/MapViewController.swift
iOS/Features/SaveJourney/Sources/SaveJourney/Presentation/SaveJourneyViewController.swift
iOS/Features/SelectSong/Sources/SelectSong/Presentation/SelectSongViewController.swift
iOS/MSCoreKit/Sources/MSKeychainStorage/MSKeychainStorage+Constants.swift
iOS/MSUIKit/Sources/MSUIKit/Cells/JourneyCell/JourneyCell.swift
iOS/MusicSpot/MusicSpot/SceneDelegate.swift

[iOS] 여정 저장 화면 전환 후 음악이 자동으로 재생되도록 변경

---

BE/musicspot/src/journey/controller/journey.controller.ts

마지막 journey 체크 시 진행 중이었는지 아닌지에 대한 여부를 확인하는 api 의 response 타입이 journey로 되어있었음
그래서 응답 형태를 dto로 수정

♻️ : 마지막 journey 진행 중 여부 확인 api response dto 로 수정

---

BE/musicspot/src/common/util/coordinate.v2.util.ts
BE/musicspot/src/journey/controller/journey.controller.ts
BE/musicspot/src/journey/service/journey.service.ts

- #361 
- journey 전달받은 coordinate 범위에 따른 journey 조회 로직 수정
- 기타 journey 조회 로직 중 version 1에 해당되는 부분 v2로 수정(coordinate 표현)
- 기존 check라는 api 명을 사용 그러나 의미와 맞지 않다고 판단
- journey?userId=userId&minCoordinate=lat lon&maxCoordinate=lat lon 형식으로 수정
- coordinate 출력 시 v1 버전(배열)로 표시
- v2에 맞게 lat lon, lat lon, ... 형식으로 변환

[BE] ✨ : coordinate 형식 변경에 따른 비지니스 로직 수정2
